"""added all times for production

Revision ID: 0671dc91c625
Revises: 1d97be4dfdec
Create Date: 2025-08-04 10:27:38.543322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0671dc91c625'
down_revision = '1d97be4dfdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_production_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pre_expansion_time_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('block_making_time_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cutting_time_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('boxing_time_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qc_time_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_production_time_min', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_production_records', schema=None) as batch_op:
        batch_op.drop_column('total_production_time_min')
        batch_op.drop_column('qc_time_min')
        batch_op.drop_column('boxing_time_min')
        batch_op.drop_column('cutting_time_min')
        batch_op.drop_column('block_making_time_min')
        batch_op.drop_column('pre_expansion_time_min')

    # ### end Alembic commands ###
