"""Add quality control table

Revision ID: 071a0a0837b6
Revises: 72076b0ad96e
Create Date: 2025-08-01 14:43:37.867212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071a0a0837b6'
down_revision = '72076b0ad96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cutting_production_id', sa.Integer(), nullable=False),
    sa.Column('cornices_count_operator', sa.Integer(), nullable=False),
    sa.Column('cornices_count_qc', sa.Integer(), nullable=False),
    sa.Column('bad_cornices_count', sa.Integer(), nullable=False),
    sa.Column('good_cornices_count', sa.Integer(), nullable=False),
    sa.Column('rated_areo_effect', sa.Integer(), nullable=False),
    sa.Column('rated_eps_binding', sa.Integer(), nullable=False),
    sa.Column('rated_wetspots', sa.Integer(), nullable=False),
    sa.Column('rated_dryness', sa.Integer(), nullable=False),
    sa.Column('rated_lines', sa.Integer(), nullable=False),
    sa.Column('qc_done_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_boxing_ready', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cutting_production_id'], ['cutting_production_records.id'], ),
    sa.ForeignKeyConstraint(['qc_done_by'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cutting_production_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_control')
    # ### end Alembic commands ###
