"""Add CuttingProductionRecord table

Revision ID: 0a274877455e
Revises: a6678ad92fb8
Create Date: 2025-08-01 12:06:52.915158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a274877455e'
down_revision = 'a6678ad92fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutting_production_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_code', sa.String(length=10), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.String(length=20), nullable=False),
    sa.Column('pre_exp_batch_no', sa.String(length=50), nullable=False),
    sa.Column('cornices_produced', sa.Integer(), nullable=False),
    sa.Column('wastage', sa.Integer(), nullable=False),
    sa.Column('date_boxed', sa.DateTime(), nullable=True),
    sa.Column('actual_production_time_min', sa.Integer(), nullable=True),
    sa.Column('boxes_made', sa.Integer(), nullable=True),
    sa.Column('waste_boxing', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cutting_production_records')
    # ### end Alembic commands ###
