"""Add Cut to profileassignment table

Revision ID: 1381add6e59d
Revises: 028054a7d322
Create Date: 2025-08-01 12:53:51.365990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1381add6e59d'
down_revision = '028054a7d322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_profile_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cut', sa.Boolean(), nullable=False, server_default=sa.false()))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_profile_assignments', schema=None) as batch_op:
        batch_op.drop_column('cut')

    # ### end Alembic commands ###
