"""added total cornices damaged to cuttingproduction

Revision ID: 1d97be4dfdec
Revises: 2d1b3720bc06
Create Date: 2025-08-04 10:11:26.035293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d97be4dfdec'
down_revision = '2d1b3720bc06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_production_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cornices_damaged', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_production_records', schema=None) as batch_op:
        batch_op.drop_column('total_cornices_damaged')

    # ### end Alembic commands ###
