"""add payroll and leave fields to operator

Revision ID: 246898935dd4
Revises: 54695c325f15
Create Date: 2025-09-19 10:06:08.480298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246898935dd4'
down_revision = '54695c325f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=False, server_default='ZAR'))
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('employment_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('work_days_per_week', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('annual_entitlement_days', sa.Float(), nullable=False, server_default='15'))
        batch_op.add_column(sa.Column('sick_entitlement_days', sa.Float(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('family_resp_days_per_year', sa.Float(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('special_study_days_per_year', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('opening_annual_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('opening_sick_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('opening_family_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('opening_special_days', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('opening_balance_asof', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operators', schema=None) as batch_op:
        batch_op.drop_column('opening_balance_asof')
        batch_op.drop_column('opening_special_days')
        batch_op.drop_column('opening_family_days')
        batch_op.drop_column('opening_sick_days')
        batch_op.drop_column('opening_annual_days')
        batch_op.drop_column('special_study_days_per_year')
        batch_op.drop_column('family_resp_days_per_year')
        batch_op.drop_column('sick_entitlement_days')
        batch_op.drop_column('annual_entitlement_days')
        batch_op.drop_column('work_days_per_week')
        batch_op.drop_column('employment_start_date')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
