"""Moulded boxing sessions + items + qc

Revision ID: 2a0fadf4a814
Revises: cc8fc302d9da
Create Date: 2025-08-08 08:59:50.735878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0fadf4a814'
down_revision = 'cc8fc302d9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moulded_boxing_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moulded_boxing_progress_profile_code'))
        batch_op.drop_index(batch_op.f('ix_moulded_boxing_progress_session_id'))

    op.drop_table('moulded_boxing_progress')
    with op.batch_alter_table('moulded_boxed_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moulded_boxed_items', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.create_table('moulded_boxing_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('profile_code', sa.VARCHAR(length=8), nullable=False),
    sa.Column('boxes_packed', sa.INTEGER(), nullable=False),
    sa.Column('leftovers', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['moulded_cornice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moulded_boxing_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moulded_boxing_progress_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moulded_boxing_progress_profile_code'), ['profile_code'], unique=False)

    # ### end Alembic commands ###
