"""Add PR16 Trimming Pausing

Revision ID: 2cdf55e5f4fa
Revises: 49bd59074e0e
Create Date: 2025-08-12 13:00:42.963220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdf55e5f4fa'
down_revision = '49bd59074e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr16_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trim_paused', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('trim_pause_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_trimming_paused_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr16_sessions', schema=None) as batch_op:
        batch_op.drop_column('total_trimming_paused_seconds')
        batch_op.drop_column('trim_pause_start')
        batch_op.drop_column('is_trim_paused')

    # ### end Alembic commands ###
