"""Added wrapping and boxing tables

Revision ID: 2d1b3720bc06
Revises: 071a0a0837b6
Create Date: 2025-08-04 07:15:22.246850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1b3720bc06'
down_revision = '071a0a0837b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cutting_production_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('pause_start', sa.DateTime(), nullable=True),
    sa.Column('total_paused_seconds', sa.Integer(), nullable=True),
    sa.Column('boxes_packed', sa.Integer(), nullable=False),
    sa.Column('leftovers', sa.Integer(), nullable=False),
    sa.Column('cycle_start', sa.Integer(), nullable=True),
    sa.Column('cycle_end', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cutting_production_id'], ['cutting_production_records.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boxing_quality_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boxing_session_id', sa.Integer(), nullable=False),
    sa.Column('qc_operator_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('boxes_checked', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('is_stock_ready', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['boxing_session_id'], ['boxing_sessions.id'], ),
    sa.ForeignKeyConstraint(['qc_operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boxing_quality_controls')
    op.drop_table('boxing_sessions')
    # ### end Alembic commands ###
