"""add pr16_stash table

Revision ID: 305c12d5fdd3
Revises: 0b8844405ce5
Create Date: 2025-08-13 10:16:01.484082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305c12d5fdd3'
down_revision = '0b8844405ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr16_stash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('material_code', sa.String(length=20), nullable=False),
    sa.Column('kg_remaining', sa.Float(), nullable=False),
    sa.Column('source_pre_expansion_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_pre_expansion_id'], ['pre_expansions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr16_stash', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pr16_stash_density'), ['density'], unique=False)
        batch_op.create_index(batch_op.f('ix_pr16_stash_material_code'), ['material_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr16_stash', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pr16_stash_material_code'))
        batch_op.drop_index(batch_op.f('ix_pr16_stash_density'))

    op.drop_table('pr16_stash')
    # ### end Alembic commands ###
