"""quality controla add onn

Revision ID: 482e51842123
Revises: 2cdf55e5f4fa
Create Date: 2025-08-13 08:19:37.288354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482e51842123'
down_revision = '2cdf55e5f4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_expansion_checklist_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('pre_expansion_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_name', sa.String(length=100), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('check1', sa.Boolean(), nullable=True),
    sa.Column('check2', sa.Boolean(), nullable=True),
    sa.Column('check3', sa.Boolean(), nullable=True),
    sa.Column('check4', sa.Boolean(), nullable=True),
    sa.Column('check5', sa.Boolean(), nullable=True),
    sa.Column('check6', sa.Boolean(), nullable=True),
    sa.Column('check7', sa.Boolean(), nullable=True),
    sa.Column('check8', sa.Boolean(), nullable=True),
    sa.Column('check9', sa.Boolean(), nullable=True),
    sa.Column('check10', sa.Boolean(), nullable=True),
    sa.Column('check11', sa.Boolean(), nullable=True),
    sa.Column('check12', sa.Boolean(), nullable=True),
    sa.Column('check13', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['pre_expansion_checklists.id'], ),
    sa.ForeignKeyConstraint(['pre_expansion_id'], ['pre_expansions.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_expansion_checklist_events')
    # ### end Alembic commands ###
