"""Add PR16 pause columns

Revision ID: 49bd59074e0e
Revises: aed897dc45a3
Create Date: 2025-08-12 11:28:22.172196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bd59074e0e'
down_revision = 'aed897dc45a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr16_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paused', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pause_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_wrapping_paused_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr16_sessions', schema=None) as batch_op:
        batch_op.drop_column('total_wrapping_paused_seconds')
        batch_op.drop_column('pause_start')
        batch_op.drop_column('is_paused')

    # ### end Alembic commands ###
