"""Add is_profile16 to blocks

Revision ID: 5386c6cc035c
Revises: 7e6cd460b97d
Create Date: 2025-08-06 15:23:03.549675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5386c6cc035c'
down_revision = '7e6cd460b97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_profile16', sa.Boolean(), nullable=False, server_default=sa.text('0')))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_column('is_profile16')

    # ### end Alembic commands ###
