"""added extrusion tables

Revision ID: 59fc26cfcf2f
Revises: dca385b5662c
Create Date: 2025-08-14 06:10:22.675039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '59fc26cfcf2f'
down_revision = 'dca385b5662c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extruded_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('length_m', sa.Float(), server_default='2.0', nullable=False),
    sa.Column('pieces_per_box', sa.Integer(), server_default='72', nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('extruders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('extruded_profile_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('gpps_kg_h', sa.Float(), nullable=True),
    sa.Column('talc_kg_h', sa.Float(), nullable=True),
    sa.Column('fire_retardant_kg_h', sa.Float(), nullable=True),
    sa.Column('recycling_kg_h', sa.Float(), nullable=True),
    sa.Column('co2_kg_h', sa.Float(), nullable=True),
    sa.Column('alcohol_l_h', sa.Float(), nullable=True),
    sa.Column('heat_table', sqlite.JSON(), server_default='{}', nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['extruded_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extruded_profile_settings', schema=None) as batch_op:
        batch_op.create_index('ix_profile_settings_profile_id_created', ['profile_id', 'created_at'], unique=False)

    op.create_table('extrusion_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extruder_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('pause_start', sa.DateTime(), nullable=True),
    sa.Column('setpoints_snapshot', sqlite.JSON(), server_default='{}', nullable=False),
    sa.Column('heat_table_snapshot', sqlite.JSON(), server_default='{}', nullable=False),
    sa.Column('pieces_produced', sa.Integer(), server_default='0', nullable=False),
    sa.Column('theoretical_boxes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['extruder_id'], ['extruders.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['extruded_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extrusion_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_extrusion_sessions_machine_status', ['extruder_id', 'status'], unique=False)
        batch_op.create_index('ix_extrusion_sessions_started_at', ['started_at'], unique=False)

    op.create_table('extrusion_cycle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reading_type', sa.Enum('ABSOLUTE', 'DELTA', name='readingtype'), nullable=False),
    sa.Column('reading_value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['extrusion_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extrusion_cycle_logs', schema=None) as batch_op:
        batch_op.create_index('ix_cycle_logs_session_time', ['session_id', 'timestamp'], unique=False)

    op.create_table('extrusion_material_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('material', sa.Enum('GPPS', 'TALC', 'FIRE_RETARDANT', 'RECYCLING', 'OIL', 'CO2', 'ALCOHOL', name='materialtype'), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'LITRE', 'BAGS_25KG', 'CANS_5L', name='usageunit'), nullable=False),
    sa.Column('quantity', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['extrusion_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extrusion_material_usages', schema=None) as batch_op:
        batch_op.create_index('ix_material_usages_session_material_time', ['session_id', 'material', 'timestamp'], unique=False)

    op.create_table('extrusion_prestart_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('answers', sqlite.JSON(), server_default='{}', nullable=False),
    sa.Column('approved', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['extrusion_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('extrusion_rate_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('gpps_kg_h', sa.Float(), nullable=True),
    sa.Column('talc_kg_h', sa.Float(), nullable=True),
    sa.Column('fire_retardant_kg_h', sa.Float(), nullable=True),
    sa.Column('recycling_kg_h', sa.Float(), nullable=True),
    sa.Column('co2_kg_h', sa.Float(), nullable=True),
    sa.Column('alcohol_l_h', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['extrusion_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'effective_from', name='uq_rateplan_session_effective')
    )
    with op.batch_alter_table('extrusion_rate_plans', schema=None) as batch_op:
        batch_op.create_index('ix_rate_plans_session_effective', ['session_id', 'effective_from'], unique=False)

    op.create_table('extrusion_run_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['extrusion_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extrusion_run_segments', schema=None) as batch_op:
        batch_op.create_index('ix_extrusion_run_segments_session', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extrusion_run_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_extrusion_run_segments_session')

    op.drop_table('extrusion_run_segments')
    with op.batch_alter_table('extrusion_rate_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_plans_session_effective')

    op.drop_table('extrusion_rate_plans')
    op.drop_table('extrusion_prestart_checklists')
    with op.batch_alter_table('extrusion_material_usages', schema=None) as batch_op:
        batch_op.drop_index('ix_material_usages_session_material_time')

    op.drop_table('extrusion_material_usages')
    with op.batch_alter_table('extrusion_cycle_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_cycle_logs_session_time')

    op.drop_table('extrusion_cycle_logs')
    with op.batch_alter_table('extrusion_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_extrusion_sessions_started_at')
        batch_op.drop_index('ix_extrusion_sessions_machine_status')

    op.drop_table('extrusion_sessions')
    with op.batch_alter_table('extruded_profile_settings', schema=None) as batch_op:
        batch_op.drop_index('ix_profile_settings_profile_id_created')

    op.drop_table('extruded_profile_settings')
    op.drop_table('extruders')
    op.drop_table('extruded_profiles')
    # ### end Alembic commands ###
