"""added PR16 statuses to production

Revision ID: 624097c1cc8b
Revises: df5ad374906d
Create Date: 2025-08-04 13:56:53.625456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624097c1cc8b'
down_revision = 'df5ad374906d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_production_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_boxable', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('qc_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_production_records', schema=None) as batch_op:
        batch_op.drop_column('qc_status')
        batch_op.drop_column('is_boxable')

    # ### end Alembic commands ###
