"""Add CuttingProductionRecord table

Revision ID: 6bcb648e4fbc
Revises: 0a274877455e
Create Date: 2025-08-01 12:09:00.663339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcb648e4fbc'
down_revision = '0a274877455e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cutting_production_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutting_production_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('block_id', sa.INTEGER(), nullable=False),
    sa.Column('block_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pre_exp_batch_no', sa.VARCHAR(length=50), nullable=False),
    sa.Column('cornices_produced', sa.INTEGER(), nullable=False),
    sa.Column('wastage', sa.INTEGER(), nullable=False),
    sa.Column('date_boxed', sa.DATETIME(), nullable=True),
    sa.Column('actual_production_time_min', sa.INTEGER(), nullable=True),
    sa.Column('boxes_made', sa.INTEGER(), nullable=True),
    sa.Column('waste_boxing', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
