"""Add is_paused

Revision ID: 72076b0ad96e
Revises: 639f9645b36d
Create Date: 2025-08-01 13:50:37.777208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72076b0ad96e'
down_revision = '639f9645b36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wire_cutting_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paused', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wire_cutting_sessions', schema=None) as batch_op:
        batch_op.drop_column('is_paused')

    # ### end Alembic commands ###
