"""Add material_code and is_pastel_captured to PreExpansion

Revision ID: 7e6cd460b97d
Revises: b9261f3570e4
Create Date: 2025-08-06 08:47:37.286999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6cd460b97d'
down_revision = 'b9261f3570e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_expansions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_pastel_captured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_expansions', schema=None) as batch_op:
        batch_op.drop_column('is_pastel_captured')
        batch_op.drop_column('material_code')

    # ### end Alembic commands ###
