"""added extrusion upgrades

Revision ID: 862dfdd3c83b
Revises: 8b7e2e6e12ab
Create Date: 2025-08-15 07:21:41.919963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862dfdd3c83b'
down_revision = '8b7e2e6e12ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extrusion_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_boxes_boxed', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extrusion_sessions', schema=None) as batch_op:
        batch_op.drop_column('actual_boxes_boxed')

    # ### end Alembic commands ###
