"""Add status to WireCuttingSession

Revision ID: 90bb5e1fa565
Revises: 
Create Date: 2025-08-01 10:31:31.516451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bb5e1fa565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wire_cutting_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wire_cutting_sessions', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
