"""Make cut stats nullable in WireCuttingSession

Revision ID: a6678ad92fb8
Revises: d2fd3252ad4b
Create Date: 2025-08-01 10:36:38.521379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6678ad92fb8'
down_revision = 'd2fd3252ad4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wire_cutting_sessions', schema=None) as batch_op:
        batch_op.alter_column('profiles_cut',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wastage_m',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('produced_length_m',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wire_cutting_sessions', schema=None) as batch_op:
        batch_op.alter_column('produced_length_m',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('wastage_m',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('profiles_cut',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
