"""PR16 Changes

Revision ID: aed897dc45a3
Revises: 2a0fadf4a814
Create Date: 2025-08-12 06:23:38.171021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed897dc45a3'
down_revision = '2a0fadf4a814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr16_quality_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('qc_operator_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['qc_operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pr16_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pr16_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glue_used_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('paper_used_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('glue_drums_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paper_rolls_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expected_paper_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('paper_loss_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wrapping_duration_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('drying_duration_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trimming_duration_min', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr16_sessions', schema=None) as batch_op:
        batch_op.drop_column('trimming_duration_min')
        batch_op.drop_column('drying_duration_min')
        batch_op.drop_column('wrapping_duration_min')
        batch_op.drop_column('paper_loss_m')
        batch_op.drop_column('expected_paper_m')
        batch_op.drop_column('paper_rolls_used')
        batch_op.drop_column('glue_drums_used')
        batch_op.drop_column('paper_used_m')
        batch_op.drop_column('glue_used_kg')

    op.drop_table('pr16_quality_checks')
    # ### end Alembic commands ###
