"""Add analytics and QC fields to boxing models

Revision ID: afb0b1ec232b
Revises: 5386c6cc035c
Create Date: 2025-08-07 06:29:08.947604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb0b1ec232b'
down_revision = '5386c6cc035c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boxing_quality_controls', schema=None) as batch_op:
    	batch_op.add_column(sa.Column('good_cornices_count', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('boxing_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producing_cycles', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_producing_cycles', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('time_per_box_min', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boxing_sessions', schema=None) as batch_op:
        batch_op.drop_column('time_per_box_min')
        batch_op.drop_column('actual_producing_cycles')
        batch_op.drop_column('producing_cycles')

    with op.batch_alter_table('boxing_quality_controls', schema=None) as batch_op:
        batch_op.drop_column('good_cornices_count')

    # ### end Alembic commands ###
