"""Add FK profile_code to CuttingProductionRecord

Revision ID: b4d8a172e4f6
Revises: f5ef37488753
Create Date: 2025-08-07 09:54:28.187587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d8a172e4f6'
down_revision = 'f5ef37488753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_production_records', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_cutting_production_records_profile_code_profiles',   # <--- ADDED
            'profiles',
            ['profile_code'],
            ['code']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_production_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
