"""add trimming_start and trimming_end to PR16TrimmingLog

Revision ID: b9261f3570e4
Revises: 624097c1cc8b
Create Date: 2025-08-05 06:37:57.156897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9261f3570e4'
down_revision = '624097c1cc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr16_trimming_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trimming_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trimming_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr16_trimming_logs', schema=None) as batch_op:
        batch_op.drop_column('trimming_end')
        batch_op.drop_column('trimming_start')

    # ### end Alembic commands ###
