"""Added Moulded Boxing another class

Revision ID: cc8fc302d9da
Revises: ef590fedcb12
Create Date: 2025-08-08 08:52:25.826796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8fc302d9da'
down_revision = 'ef590fedcb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moulded_boxing_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('profile_code', sa.String(length=8), nullable=False),
    sa.Column('boxes_packed', sa.Integer(), nullable=False),
    sa.Column('leftovers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['moulded_cornice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moulded_boxing_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moulded_boxing_progress_profile_code'), ['profile_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_moulded_boxing_progress_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moulded_boxing_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moulded_boxing_progress_session_id'))
        batch_op.drop_index(batch_op.f('ix_moulded_boxing_progress_profile_code'))

    op.drop_table('moulded_boxing_progress')
    # ### end Alembic commands ###
