"""added PR16 Tables

Revision ID: df5ad374906d
Revises: 0671dc91c625
Create Date: 2025-08-04 13:26:57.261726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5ad374906d'
down_revision = '0671dc91c625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr16_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('wrapping_end', sa.DateTime(), nullable=True),
    sa.Column('drying_start', sa.DateTime(), nullable=True),
    sa.Column('drying_end', sa.DateTime(), nullable=True),
    sa.Column('trimming_start', sa.DateTime(), nullable=True),
    sa.Column('trimming_end', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('wrapped_cornices', sa.Integer(), nullable=True),
    sa.Column('trimmed_cornices', sa.Integer(), nullable=True),
    sa.Column('boxed_cornices', sa.Integer(), nullable=True),
    sa.Column('wrapping_damage', sa.Integer(), nullable=True),
    sa.Column('trimming_damage', sa.Integer(), nullable=True),
    sa.Column('total_damage', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr16_resource_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('resource_type', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pr16_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr16_trimming_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cornices_trimmed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pr16_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr16_wrapping_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cornices_wrapped', sa.Integer(), nullable=True),
    sa.Column('glue_used', sa.Float(), nullable=True),
    sa.Column('paper_used', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pr16_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr16_wrapping_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('cornices_wrapped', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['pr16_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr16_wrapping_production')
    op.drop_table('pr16_wrapping_logs')
    op.drop_table('pr16_trimming_logs')
    op.drop_table('pr16_resource_usages')
    op.drop_table('pr16_sessions')
    # ### end Alembic commands ###
