"""Added Moulded Boxing Models

Revision ID: ef590fedcb12
Revises: aa4bbc935e21
Create Date: 2025-08-08 08:34:33.664248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef590fedcb12'
down_revision = 'aa4bbc935e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moulded_boxing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moulded_session_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('pause_start', sa.DateTime(), nullable=True),
    sa.Column('total_paused_seconds', sa.Integer(), nullable=True),
    sa.Column('total_boxes', sa.Integer(), nullable=True),
    sa.Column('total_leftovers', sa.Integer(), nullable=True),
    sa.Column('time_per_box_min', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['moulded_session_id'], ['moulded_cornice_sessions.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moulded_boxing_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moulded_boxing_sessions_moulded_session_id'), ['moulded_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moulded_boxing_sessions_operator_id'), ['operator_id'], unique=False)

    op.create_table('moulded_boxed_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('profile_code', sa.String(length=8), nullable=False),
    sa.Column('boxes_packed', sa.Integer(), nullable=False),
    sa.Column('leftovers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['moulded_boxing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moulded_boxed_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moulded_boxed_items_session_id'), ['session_id'], unique=False)

    op.create_table('moulded_boxing_quality_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('qc_operator_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('boxes_checked', sa.Integer(), nullable=False),
    sa.Column('good_cornices_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('is_stock_ready', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['qc_operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['moulded_boxing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moulded_boxing_quality_controls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moulded_boxing_quality_controls_qc_operator_id'), ['qc_operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moulded_boxing_quality_controls_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moulded_boxing_quality_controls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moulded_boxing_quality_controls_session_id'))
        batch_op.drop_index(batch_op.f('ix_moulded_boxing_quality_controls_qc_operator_id'))

    op.drop_table('moulded_boxing_quality_controls')
    with op.batch_alter_table('moulded_boxed_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moulded_boxed_items_session_id'))

    op.drop_table('moulded_boxed_items')
    with op.batch_alter_table('moulded_boxing_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moulded_boxing_sessions_operator_id'))
        batch_op.drop_index(batch_op.f('ix_moulded_boxing_sessions_moulded_session_id'))

    op.drop_table('moulded_boxing_sessions')
    # ### end Alembic commands ###
