"""Add LeftoverCornice table

Revision ID: f5ef37488753
Revises: afb0b1ec232b
Create Date: 2025-08-07 07:48:29.698681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ef37488753'
down_revision = 'afb0b1ec232b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leftover_cornices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_code', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('boxing_session_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_in_session_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boxing_session_id'], ['boxing_sessions.id'], ),
    sa.ForeignKeyConstraint(['profile_code'], ['profiles.code'], ),
    sa.ForeignKeyConstraint(['used_in_session_id'], ['boxing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leftover_cornices')
    # ### end Alembic commands ###
